# Generated by Django 6.0 on 2026-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
